# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sprint1_john.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 729)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(247, 247, 255);")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_menu = QtWidgets.QFrame(self.main_frame)
        self.top_menu.setMaximumSize(QtCore.QSize(16777215, 70))
        self.top_menu.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(255, 90, 255, 255), stop:0.477833 rgba(255, 255, 255, 255), stop:0.970443 rgba(57, 224, 55, 255));")
        self.top_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_menu.setObjectName("top_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.top_menu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_menu_buttons = QtWidgets.QFrame(self.top_menu)
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(1.0, 0.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 90, 255))
        gradient.setColorAt(0.477833, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.970443, QtGui.QColor(57, 224, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 90, 255))
        gradient.setColorAt(0.477833, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.970443, QtGui.QColor(57, 224, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 90, 255))
        gradient.setColorAt(0.477833, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.970443, QtGui.QColor(57, 224, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 90, 255))
        gradient.setColorAt(0.477833, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.970443, QtGui.QColor(57, 224, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 90, 255))
        gradient.setColorAt(0.477833, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.970443, QtGui.QColor(57, 224, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 90, 255))
        gradient.setColorAt(0.477833, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.970443, QtGui.QColor(57, 224, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 90, 255))
        gradient.setColorAt(0.477833, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.970443, QtGui.QColor(57, 224, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 90, 255))
        gradient.setColorAt(0.477833, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.970443, QtGui.QColor(57, 224, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 0.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 90, 255))
        gradient.setColorAt(0.477833, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.970443, QtGui.QColor(57, 224, 55))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.top_menu_buttons.setPalette(palette)
        self.top_menu_buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_menu_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_menu_buttons.setObjectName("top_menu_buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_menu_buttons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.homeButton = QtWidgets.QPushButton(self.top_menu_buttons)
        self.homeButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.homeButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(253, 255, 199);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.homeButton.setObjectName("homeButton")
        self.horizontalLayout.addWidget(self.homeButton)
        self.constantButton = QtWidgets.QPushButton(self.top_menu_buttons)
        self.constantButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(253, 255, 199);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.constantButton.setObjectName("constantButton")
        self.horizontalLayout.addWidget(self.constantButton)
        self.verticalLayout_3.addWidget(self.top_menu_buttons)
        self.verticalLayout_2.addWidget(self.top_menu)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.main_body = QtWidgets.QFrame(self.main_frame)
        self.main_body.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_body)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.home_page)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.home_page)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.home_page)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_13.addWidget(self.lineEdit_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.addButton = QtWidgets.QPushButton(self.home_page)
        self.addButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_14.addWidget(self.addButton)
        self.viewButton = QtWidgets.QPushButton(self.home_page)
        self.viewButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.viewButton.setObjectName("viewButton")
        self.horizontalLayout_14.addWidget(self.viewButton)
        self.deleteButton = QtWidgets.QPushButton(self.home_page)
        self.deleteButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_14.addWidget(self.deleteButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.homeTable = QtWidgets.QTableWidget(self.home_page)
        self.homeTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.homeTable.setFont(font)
        self.homeTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.homeTable.setObjectName("homeTable")
        self.homeTable.setColumnCount(3)
        self.homeTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.homeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.homeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.homeTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_5.addWidget(self.homeTable)
        self.stackedWidget.addWidget(self.home_page)
        self.import_page = QtWidgets.QWidget()
        self.import_page.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.import_page.setStyleSheet("tabwidget.setStyleSheet(\"QTabWidget::pane { border: 0; }\");")
        self.import_page.setObjectName("import_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.import_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_50 = QtWidgets.QLabel(self.import_page)
        self.label_50.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_6.addWidget(self.label_50, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem1)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.pushButton = QtWidgets.QPushButton(self.import_page)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_36.addWidget(self.pushButton)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.import_page)
        self.lineEdit_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_36.addWidget(self.lineEdit_18)
        self.verticalLayout_35.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.pushButton_16 = QtWidgets.QPushButton(self.import_page)
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_37.addWidget(self.pushButton_16)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.import_page)
        self.lineEdit_19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_37.addWidget(self.lineEdit_19)
        self.verticalLayout_35.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_35.addLayout(self.verticalLayout_35)
        spacerItem2 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem3)
        self.pushButton_15 = QtWidgets.QPushButton(self.import_page)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_38.addWidget(self.pushButton_15)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_38)
        self.frame_16 = QtWidgets.QFrame(self.import_page)
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_6.addWidget(self.frame_16)
        self.stackedWidget.addWidget(self.import_page)
        self.constants_page = QtWidgets.QWidget()
        self.constants_page.setObjectName("constants_page")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.constants_page)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_49 = QtWidgets.QLabel(self.constants_page)
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_36.addWidget(self.label_49, 0, QtCore.Qt.AlignHCenter)
        self.constantTable = QtWidgets.QTableWidget(self.constants_page)
        self.constantTable.setObjectName("constantTable")
        self.constantTable.setColumnCount(0)
        self.constantTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.constantTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.constantTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.constantTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.constantTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.constantTable.setVerticalHeaderItem(4, item)
        self.verticalLayout_36.addWidget(self.constantTable)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem5)
        self.pushButton_17 = QtWidgets.QPushButton(self.constants_page)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_40.addWidget(self.pushButton_17)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem6)
        self.verticalLayout_36.addLayout(self.horizontalLayout_40)
        self.stackedWidget.addWidget(self.constants_page)
        self.analyse_page = QtWidgets.QWidget()
        self.analyse_page.setObjectName("analyse_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.analyse_page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_48 = QtWidgets.QLabel(self.analyse_page)
        self.label_48.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_7.addWidget(self.label_48, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.tabWidget = QtWidgets.QTabWidget(self.analyse_page)
        self.tabWidget.setObjectName("tabWidget")
        self.Run1 = QtWidgets.QWidget()
        self.Run1.setObjectName("Run1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Run1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.analysisTable = QtWidgets.QTableWidget(self.Run1)
        self.analysisTable.setObjectName("analysisTable")
        self.analysisTable.setColumnCount(2)
        self.analysisTable.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.analysisTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.analysisTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.analysisTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.analysisTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.analysisTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.analysisTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout_8.addWidget(self.analysisTable)
        self.tabWidget.addTab(self.Run1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_39.addWidget(self.tabWidget)
        self.verticalLayout_7.addLayout(self.horizontalLayout_39)
        self.summaryTable = QtWidgets.QTableWidget(self.analyse_page)
        self.summaryTable.setObjectName("summaryTable")
        self.summaryTable.setColumnCount(9)
        self.summaryTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.summaryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.summaryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.summaryTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.summaryTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.summaryTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.summaryTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.summaryTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.summaryTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.summaryTable.setHorizontalHeaderItem(8, item)
        self.verticalLayout_7.addWidget(self.summaryTable)
        self.stackedWidget.addWidget(self.analyse_page)
        self.add_page = QtWidgets.QWidget()
        self.add_page.setObjectName("add_page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.add_page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.add_page)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_10.addWidget(self.label_17, 0, QtCore.Qt.AlignHCenter)
        self.frame_6 = QtWidgets.QFrame(self.add_page)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 10))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_10.addWidget(self.frame_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.add_page)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.add_page)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_4.addWidget(self.lineEdit_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_19 = QtWidgets.QLabel(self.add_page)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_5.addWidget(self.label_19)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.add_page)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_5.addWidget(self.lineEdit_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        spacerItem8 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.pushButton_7 = QtWidgets.QPushButton(self.add_page)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_10.addWidget(self.pushButton_7)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.frame_5 = QtWidgets.QFrame(self.add_page)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_10.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.add_page)
        self.viewequipment_page = QtWidgets.QWidget()
        self.viewequipment_page.setObjectName("viewequipment_page")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.viewequipment_page)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_33 = QtWidgets.QLabel(self.viewequipment_page)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_29.addWidget(self.label_33, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem11)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_34 = QtWidgets.QLabel(self.viewequipment_page)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_26.addWidget(self.label_34)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.viewequipment_page)
        self.lineEdit_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_26.addWidget(self.lineEdit_14)
        self.verticalLayout_28.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_35 = QtWidgets.QLabel(self.viewequipment_page)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_27.addWidget(self.label_35)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.viewequipment_page)
        self.lineEdit_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_27.addWidget(self.lineEdit_15)
        self.verticalLayout_28.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_25.addLayout(self.verticalLayout_28)
        spacerItem12 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem12)
        self.verticalLayout_29.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem13)
        self.pushButton_13 = QtWidgets.QPushButton(self.viewequipment_page)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_28.addWidget(self.pushButton_13)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem14)
        self.verticalLayout_29.addLayout(self.horizontalLayout_28)
        self.frame_13 = QtWidgets.QFrame(self.viewequipment_page)
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_29.addWidget(self.frame_13)
        self.stackedWidget.addWidget(self.viewequipment_page)
        self.addequipment_page = QtWidgets.QWidget()
        self.addequipment_page.setObjectName("addequipment_page")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.addequipment_page)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_36 = QtWidgets.QLabel(self.addequipment_page)
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_31.addWidget(self.label_36, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem15)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_37 = QtWidgets.QLabel(self.addequipment_page)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_30.addWidget(self.label_37)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.addequipment_page)
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_30.addWidget(self.lineEdit_16)
        self.verticalLayout_30.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_38 = QtWidgets.QLabel(self.addequipment_page)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_31.addWidget(self.label_38)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.addequipment_page)
        self.lineEdit_17.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_31.addWidget(self.lineEdit_17)
        self.verticalLayout_30.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_29.addLayout(self.verticalLayout_30)
        spacerItem16 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem16)
        self.verticalLayout_31.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem17)
        self.pushButton_14 = QtWidgets.QPushButton(self.addequipment_page)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_32.addWidget(self.pushButton_14)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem18)
        self.verticalLayout_31.addLayout(self.horizontalLayout_32)
        self.frame_14 = QtWidgets.QFrame(self.addequipment_page)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_31.addWidget(self.frame_14)
        self.stackedWidget.addWidget(self.addequipment_page)
        self.viewclientinfo_page = QtWidgets.QWidget()
        self.viewclientinfo_page.setObjectName("viewclientinfo_page")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.viewclientinfo_page)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_16 = QtWidgets.QLabel(self.viewclientinfo_page)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_18.addWidget(self.label_16, 0, QtCore.Qt.AlignHCenter)
        self.horizontalFrame_6 = QtWidgets.QFrame(self.viewclientinfo_page)
        self.horizontalFrame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_7.setContentsMargins(-1, -1, 11, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.horizontalFrame_6)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.label_13 = QtWidgets.QLabel(self.horizontalFrame_6)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.label_11 = QtWidgets.QLabel(self.horizontalFrame_6)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_13.addWidget(self.label_11)
        self.label_9 = QtWidgets.QLabel(self.horizontalFrame_6)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.horizontalFrame_6)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_17.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.label_15 = QtWidgets.QLabel(self.horizontalFrame_6)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_17.addWidget(self.label_15, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.horizontalFrame_6)
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_17.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.horizontalFrame_6)
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_17.addWidget(self.lineEdit_9)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalFrame_6)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.verticalLayout_18.addWidget(self.horizontalFrame_6)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.compareButton = QtWidgets.QPushButton(self.viewclientinfo_page)
        self.compareButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.compareButton.setObjectName("compareButton")
        self.horizontalLayout_15.addWidget(self.compareButton)
        self.addnewequipmentButton = QtWidgets.QPushButton(self.viewclientinfo_page)
        self.addnewequipmentButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.addnewequipmentButton.setObjectName("addnewequipmentButton")
        self.horizontalLayout_15.addWidget(self.addnewequipmentButton)
        self.viewequipmentButton = QtWidgets.QPushButton(self.viewclientinfo_page)
        self.viewequipmentButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.viewequipmentButton.setObjectName("viewequipmentButton")
        self.horizontalLayout_15.addWidget(self.viewequipmentButton)
        self.deleteequipmentButton = QtWidgets.QPushButton(self.viewclientinfo_page)
        self.deleteequipmentButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.deleteequipmentButton.setObjectName("deleteequipmentButton")
        self.horizontalLayout_15.addWidget(self.deleteequipmentButton)
        self.verticalLayout_18.addLayout(self.horizontalLayout_15)
        self.clientTable = QtWidgets.QTableWidget(self.viewclientinfo_page)
        self.clientTable.setObjectName("clientTable")
        self.clientTable.setColumnCount(3)
        self.clientTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.clientTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.clientTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.clientTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_18.addWidget(self.clientTable)
        self.stackedWidget.addWidget(self.viewclientinfo_page)
        self.compare_page = QtWidgets.QWidget()
        self.compare_page.setObjectName("compare_page")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.compare_page)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_47 = QtWidgets.QLabel(self.compare_page)
        self.label_47.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_34.addWidget(self.label_47, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(-1, -1, 11, -1)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem19 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem19)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_39 = QtWidgets.QLabel(self.compare_page)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_32.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.compare_page)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_32.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.compare_page)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_32.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.compare_page)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_32.addWidget(self.label_42)
        self.horizontalLayout_33.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_43 = QtWidgets.QLabel(self.compare_page)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_33.addWidget(self.label_43, 0, QtCore.Qt.AlignHCenter)
        self.label_45 = QtWidgets.QLabel(self.compare_page)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_33.addWidget(self.label_45, 0, QtCore.Qt.AlignHCenter)
        self.label_46 = QtWidgets.QLabel(self.compare_page)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_33.addWidget(self.label_46, 0, QtCore.Qt.AlignHCenter)
        self.label_44 = QtWidgets.QLabel(self.compare_page)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_33.addWidget(self.label_44, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_33.addLayout(self.verticalLayout_33)
        spacerItem20 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem20)
        self.verticalLayout_34.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.importButton = QtWidgets.QPushButton(self.compare_page)
        self.importButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_34.addWidget(self.importButton)
        self.analyseButton = QtWidgets.QPushButton(self.compare_page)
        self.analyseButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.analyseButton.setObjectName("analyseButton")
        self.horizontalLayout_34.addWidget(self.analyseButton)
        self.viewequipmentButton_3 = QtWidgets.QPushButton(self.compare_page)
        self.viewequipmentButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(211, 213, 213);\n"
"color:black;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: black;\n"
"font:bold 16px;\n"
"padding: 6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(83, 82, 82);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: white;\n"
"}\n"
"")
        self.viewequipmentButton_3.setObjectName("viewequipmentButton_3")
        self.horizontalLayout_34.addWidget(self.viewequipmentButton_3)
        self.verticalLayout_34.addLayout(self.horizontalLayout_34)
        self.compareTable = QtWidgets.QTableWidget(self.compare_page)
        self.compareTable.setObjectName("compareTable")
        self.compareTable.setColumnCount(4)
        self.compareTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.compareTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.compareTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.compareTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.compareTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout_34.addWidget(self.compareTable)
        self.stackedWidget.addWidget(self.compare_page)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.main_body)
        self.verticalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeButton.setText(_translate("MainWindow", "HOME"))
        self.constantButton.setText(_translate("MainWindow", "CONSTANTS"))
        self.label_4.setText(_translate("MainWindow", "HOME"))
        self.label_12.setText(_translate("MainWindow", "Search: "))
        self.addButton.setText(_translate("MainWindow", "Add New Client"))
        self.viewButton.setText(_translate("MainWindow", "View/Edit Client Information"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Client"))
        item = self.homeTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SELECT"))
        item = self.homeTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CAL NUMBER"))
        item = self.homeTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CLIENT NAME"))
        self.label_50.setText(_translate("MainWindow", "Import Files"))
        self.pushButton.setText(_translate("MainWindow", "Client File"))
        self.pushButton_16.setText(_translate("MainWindow", "Lab FIle"))
        self.pushButton_15.setText(_translate("MainWindow", "Upload"))
        self.label_49.setText(_translate("MainWindow", "Constants"))
        item = self.constantTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "MA"))
        item = self.constantTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "KK"))
        item = self.constantTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "WE"))
        item = self.constantTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Constant 1"))
        item = self.constantTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Constant 2"))
        self.pushButton_17.setText(_translate("MainWindow", "Save"))
        self.label_48.setText(_translate("MainWindow", "Analysis"))
        item = self.analysisTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Monitor 1"))
        item = self.analysisTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.analysisTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Chamber (Client)"))
        item = self.analysisTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Standard (MEFAC)"))
        item = self.analysisTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Current pA (Before)"))
        item = self.analysisTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Current pA (After)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Run1), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        item = self.summaryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Beam Quality"))
        item = self.summaryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "E_eff"))
        item = self.summaryTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Run1_NK"))
        item = self.summaryTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Run2_NK"))
        item = self.summaryTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Run3_NK"))
        item = self.summaryTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Average"))
        item = self.summaryTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Run1/Average"))
        item = self.summaryTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Run2/Average"))
        item = self.summaryTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Run3/Average"))
        self.label_17.setText(_translate("MainWindow", "ADD NEW CLIENT"))
        self.label_18.setText(_translate("MainWindow", "CAL Number"))
        self.label_19.setText(_translate("MainWindow", "Client Name"))
        self.pushButton_7.setText(_translate("MainWindow", "Submit"))
        self.label_33.setText(_translate("MainWindow", "View/Edit Equipment"))
        self.label_34.setText(_translate("MainWindow", "Serial Number"))
        self.label_35.setText(_translate("MainWindow", "Make/Model Number"))
        self.pushButton_13.setText(_translate("MainWindow", "Update"))
        self.label_36.setText(_translate("MainWindow", "Add New Equipment"))
        self.label_37.setText(_translate("MainWindow", "Serial Number"))
        self.label_38.setText(_translate("MainWindow", "Make/Model Number"))
        self.pushButton_14.setText(_translate("MainWindow", "Add"))
        self.label_16.setText(_translate("MainWindow", "CLIENT INFORMATION"))
        self.label_10.setText(_translate("MainWindow", "CAL Number"))
        self.label_13.setText(_translate("MainWindow", "Client Name"))
        self.label_11.setText(_translate("MainWindow", "Address 1"))
        self.label_9.setText(_translate("MainWindow", "Address 2"))
        self.label_14.setText(_translate("MainWindow", "CAL00001"))
        self.label_15.setText(_translate("MainWindow", "Winnie"))
        self.pushButton_5.setText(_translate("MainWindow", "Update"))
        self.compareButton.setText(_translate("MainWindow", "Compare/Analysis"))
        self.addnewequipmentButton.setText(_translate("MainWindow", "Add New Equipment"))
        self.viewequipmentButton.setText(_translate("MainWindow", "View/Edit Equipment"))
        self.deleteequipmentButton.setText(_translate("MainWindow", "Delete Equipment"))
        item = self.clientTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SELECT"))
        item = self.clientTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "SERIAL NUMBER"))
        item = self.clientTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MAKE/MODEL"))
        self.label_47.setText(_translate("MainWindow", "Compare/Analysis"))
        self.label_39.setText(_translate("MainWindow", "CAL Number"))
        self.label_40.setText(_translate("MainWindow", "Client Name"))
        self.label_41.setText(_translate("MainWindow", "Serial Number"))
        self.label_42.setText(_translate("MainWindow", "Make/Model Number"))
        self.label_43.setText(_translate("MainWindow", "CAL00001"))
        self.label_45.setText(_translate("MainWindow", "TextLabel"))
        self.label_46.setText(_translate("MainWindow", "TextLabel"))
        self.label_44.setText(_translate("MainWindow", "Winnie"))
        self.importButton.setText(_translate("MainWindow", "Import Raw Files"))
        self.analyseButton.setText(_translate("MainWindow", "Analyse Run"))
        self.viewequipmentButton_3.setText(_translate("MainWindow", "Delete Run"))
        item = self.compareTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "RUN NUMBER"))
        item = self.compareTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CLIENT RAW FILE"))
        item = self.compareTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "LAB RAW FILE"))
        item = self.compareTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "UPLOADED DATETIME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
